site:
  name: BgGPT
  site: 'https://insait-institute.github.io'
  base: '/BgGPT'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: BgGPT
    template: '%s — BgGPT'
  description: 'State-of-the-art generative AI for the Bulgarian language, created by INSAIT for Bulgarian users, institutions, and organizations.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: BgGPT
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%'
      robots:
        index: false

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: false

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: false

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
